site_name: Chilka docs
docs_dir: docs_source
site_dir: docs

theme:
  name: "material"

plugins:
  - search
  - mkdocstrings
  
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
  - index.md
  - tutorials.md
  - how-to-guides.md
  - reference.md
  - explanation.md
